spring:
  application:
    name: api-platform-backend
  datasource:
    url: jdbc:mysql://localhost:3306/api-platform
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  servlet:
    context-path: /api
  port: 8080
dubbo:
  application:
    name: api-platform-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    id: -registry
    address: nacos://localhost:8848
nacos:
  discovery:
    server-addr: localhost:8848

